//created on: Oct 7, 2015
package retailtrackerdrl

//list any import classes here.
import org.jboss.brmspojos.CustomerObj;
import org.jboss.brmspojos.Department;


declare CustomerObj
    @role ( event )
end

declare CustomerVisitCount

   customerId : Integer
   deptName: String
   visitCount: Integer

end



rule "Customer entered a department and is not in a list of special departments and makes more than 3 moves"
no-loop
    when
        //conditions
         
        $customer : CustomerObj( $cid: custId, $p: location, $cnt : deptVisitCount )
        Department( $dname: departmentName, $dloc: deptLocation,
                $dloc.contains( $p ))
    then
        //actions
        
        $customer.setDeptVisitCount( $customer.getDeptVisitCount() + 1 );
        update( $customer );
        System.out.println( "customer " + $cid);
        System.out.println( "customer visit count" + $customer.getDeptVisitCount());

end

/*rule "Customer in special department and moves"
    when
        $customer: CustomerObj(  )
        Number( intValue  > 3) from accumulate (
            $t: CustomerObj(  ) over window:time ( 5s ),
            count($t)
        )
    then
                System.out.println(" More than 3 customers in less than 5 seconds");
end

rule "Customer entered a department"
no-loop
    when
        //conditions
         
        $customer : CustomerObj( $cid: custId, $p: location, $cnt : deptVisitCount )
        Department( $dname: departmentName, $dloc: deptLocation,
                $dloc.contains( $p ) and exists)
    then
        //actions
          System.out.println(" into then");
        $customer.setDeptVisitCount( $customer.getDeptVisitCount() + 1 );
        update( $customer );
        System.out.println( "customer " + $cid);
        System.out.println( "customer visit count" + $customer.getDeptVisitCount());
        
        
       
end*/
